quarkus:
  datasource:
    password: sa
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:prueba;
    username: sa
  hibernate-orm:
    sql-load-script: import.sql
    database:
      generation: drop-and-create
  profile: dev