quarkus:
  datasource:
    password: sa
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:prueba;
    username: sa
  hibernate-orm:
    sql-load-script: import.sql
    database:
      generation: drop-and-create
  log:
    category:
      "org.hibernate.SQL":
        level: DEBUG
      "org.hibernate.type.descriptor.sql.BasicBinder":
        level: DEBUG
  profile: dev